import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { io } from 'socket.io-client'
import { useState } from 'react'

const socket = io("http://localhost:5000");

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [message, setmessage] = useState("");
  const [list, setlist] = useState([]);

  const handleSendMessage = () => {
    //サーバーへ送信
    socket.emit("send_message", { message: message });
    setmessage("");
  }

  //サーバから受信
  socket.on("receive_data", (data) => {
    console.log(data);
    setlist([...list, data]);
  })
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <div className={styles.container}>
        <h2>チャットアプリ</h2>
        <div className={styles.chatInputButton}>
          <input type='text' placeholder='content' value={message} onChange={(e) => setmessage(e.target.value)} />
          <button onClick={handleSendMessage}>チャット送信</button>
        </div>
        {list.map((chat)=>(
          <div className={styles.chatArea} key={chat.message}>
            {chat.message}
          </div>
        ))}
      </div>
    </>
  )
}
